# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby-debug-ide` gem.
# Please instead update this file by running `bin/tapioca gem ruby-debug-ide`.

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/breakpoints.rb#2
Debugger::AddBreakpoint = Debase::AddBreakpoint

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/breakpoints.rb#67
Debugger::BreakpointsCommand = Debase::BreakpointsCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/catchpoint.rb#2
Debugger::CatchCommand = Debase::CatchCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/command.rb#13
Debugger::Command = Debase::Command

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/condition.rb#3
Debugger::ConditionCommand = Debase::ConditionCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/stepping.rb#87
Debugger::ContinueCommand = Debase::ContinueCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/ide_processor.rb#133
Debugger::ControlState = Debase::ControlState

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/breakpoints.rb#91
Debugger::DeleteBreakpointCommand = Debase::DeleteBreakpointCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/control.rb#131
Debugger::DetachCommand = Debase::DetachCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/enable.rb#125
Debugger::DisableCommand = Debase::DisableCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/frame.rb#92
Debugger::DownCommand = Debase::DownCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/enable.rb#47
Debugger::EnableCommand = Debase::EnableCommand

# Mix-in module to assist in command parsing.
#
# source://ruby-debug-ide//lib/ruby-debug-ide/commands/enable.rb#3
Debugger::EnableDisableFunctions = Debase::EnableDisableFunctions

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/eval.rb#3
Debugger::EvalCommand = Debase::EvalCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/event_processor.rb#5
Debugger::EventProcessor = Debase::EventProcessor

# source://ruby-debug-ide//lib/ruby-debug-ide.rb#225
Debugger::Exception = Debase::Exception

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/file_filtering.rb#36
Debugger::ExcludeFile = Debase::ExcludeFile

# source://ruby-debug-ide//lib/ruby-debug-ide/xml_printer.rb#13
Debugger::ExecError = Debase::ExecError

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/expression_info.rb#6
Debugger::ExpressionInfoCommand = Debase::ExpressionInfoCommand

# source://ruby-debug-ide//lib/ruby-debug-ide.rb#10
Debugger::FRONT_END = T.let(T.unsafe(nil), String)

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/file_filtering.rb#70
Debugger::FileFilterCommand = Debase::FileFilterCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/stepping.rb#57
Debugger::FinishCommand = Debase::FinishCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/frame.rb#121
Debugger::FrameCommand = Debase::FrameCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/frame.rb#3
Debugger::FrameFunctions = Debase::FrameFunctions

# source://ruby-debug-ide//lib/ruby-debug-ide/version.rb#2
Debugger::IDE_VERSION = T.let(T.unsafe(nil), String)

# source://ruby-debug-ide//lib/ruby-debug-ide/ide_processor.rb#5
Debugger::IdeCommandProcessor = Debase::IdeCommandProcessor

# source://ruby-debug-ide//lib/ruby-debug-ide/ide_processor.rb#74
Debugger::IdeControlCommandProcessor = Debase::IdeControlCommandProcessor

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/file_filtering.rb#2
Debugger::IncludeFile = Debase::IncludeFile

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/inspect.rb#4
Debugger::InspectCommand = Debase::InspectCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/interface.rb#4
Debugger::Interface = Debase::Interface

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/control.rb#101
Debugger::InterruptCommand = Debase::InterruptCommand

# Implements debugger "jump" command
#
# source://ruby-debug-ide//lib/ruby-debug-ide/commands/jump.rb#4
Debugger::JumpCommand = Debase::JumpCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/load.rb#2
Debugger::LoadCommand = Debase::LoadCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/interface.rb#7
Debugger::LocalInterface = Debase::LocalInterface

# source://ruby-debug-ide//lib/ruby-debug-ide/xml_printer.rb#31
Debugger::MemoryLimitError = Debase::MemoryLimitError

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/stepping.rb#2
Debugger::NextCommand = Debase::NextCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/xml_printer.rb#7
Debugger::OverflowMessageType = Debase::OverflowMessageType

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/eval.rb#40
Debugger::PPCommand = Debase::PPCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/helper.rb#3
Debugger::ParseFunctions = Debase::ParseFunctions

# Implements debugger "pause" command
#
# source://ruby-debug-ide//lib/ruby-debug-ide/commands/pause.rb#4
Debugger::PauseCommand = Debase::PauseCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/control.rb#2
Debugger::QuitCommand = Debase::QuitCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/interface.rb#11
Debugger::RemoteInterface = Debase::RemoteInterface

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/control.rb#32
Debugger::RestartCommand = Debase::RestartCommand

# Implements debugger "set_type" command
#
# source://ruby-debug-ide//lib/ruby-debug-ide/commands/set_type.rb#4
Debugger::SetTypeCommand = Debase::SetTypeCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/xml_printer.rb#23
Debugger::SimpleTimeLimitError = Debase::SimpleTimeLimitError

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/control.rb#75
Debugger::StartCommand = Debase::StartCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/ide_processor.rb#101
Debugger::State = Debase::State

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/stepping.rb#30
Debugger::StepCommand = Debase::StepCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/threads.rb#121
Debugger::ThreadCurrentCommand = Debase::ThreadCurrentCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/threads.rb#62
Debugger::ThreadInspectCommand = Debase::ThreadInspectCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/threads.rb#2
Debugger::ThreadListCommand = Debase::ThreadListCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/threads.rb#145
Debugger::ThreadResumeCommand = Debase::ThreadResumeCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/threads.rb#87
Debugger::ThreadStopCommand = Debase::ThreadStopCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/threads.rb#26
Debugger::ThreadSwitchCommand = Debase::ThreadSwitchCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/xml_printer.rb#34
Debugger::TimeLimitError = Debase::TimeLimitError

# source://ruby-debug-ide//lib/ruby-debug-ide/thread_alias.rb#2
Debugger::TimeoutHandler = Debase::TimeoutHandler

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/frame.rb#63
Debugger::UpCommand = Debase::UpCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/variables.rb#2
Debugger::VarConstantCommand = Debase::VarConstantCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/variables.rb#31
Debugger::VarGlobalCommand = Debase::VarGlobalCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/variables.rb#63
Debugger::VarInstanceCommand = Debase::VarInstanceCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/variables.rb#123
Debugger::VarLocalCommand = Debase::VarLocalCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/commands/frame.rb#35
Debugger::WhereCommand = Debase::WhereCommand

# source://ruby-debug-ide//lib/ruby-debug-ide/xml_printer.rb#37
Debugger::XmlPrinter = Debase::XmlPrinter
