# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `spring-watcher-listen` gem.
# Please instead update this file by running `bin/tapioca gem spring-watcher-listen`.

# source://spring-watcher-listen//lib/spring/watcher/listen.rb#17
module Spring
  class << self
    # source://spring/2.1.1/lib/spring/configuration.rb#19
    def after_fork(&block); end

    # source://spring/2.1.1/lib/spring/configuration.rb#15
    def after_fork_callbacks; end

    # source://spring/2.1.1/lib/spring/configuration.rb#5
    def application_root; end

    # source://spring/2.1.1/lib/spring/configuration.rb#5
    def application_root=(_arg0); end

    # source://spring/2.1.1/lib/spring/configuration.rb#27
    def application_root_path; end

    # source://spring/2.1.1/lib/spring/configuration.rb#7
    def gemfile; end

    # source://spring/2.1.1/lib/spring/configuration.rb#40
    def project_root_path; end

    # source://spring/2.1.1/lib/spring/configuration.rb#5
    def quiet; end

    # source://spring/2.1.1/lib/spring/configuration.rb#5
    def quiet=(_arg0); end

    # source://spring/2.1.1/lib/spring/configuration.rb#23
    def verify_environment; end

    # source://spring/2.1.1/lib/spring/watcher.rb#27
    def watch(*items); end

    # source://spring/2.1.1/lib/spring/watcher.rb#6
    def watch_interval; end

    # source://spring/2.1.1/lib/spring/watcher.rb#6
    def watch_interval=(_arg0); end

    # source://spring/2.1.1/lib/spring/watcher.rb#8
    def watch_method; end

    # source://spring/2.1.1/lib/spring/watcher.rb#11
    def watch_method=(method); end

    # source://spring/2.1.1/lib/spring/watcher.rb#23
    def watcher; end

    # source://spring/2.1.1/lib/spring/watcher.rb#7
    def watcher=(_arg0); end

    private

    # source://spring/2.1.1/lib/spring/configuration.rb#46
    def find_project_root(current_dir); end
  end
end

# source://spring-watcher-listen//lib/spring/watcher/listen.rb#18
module Spring::Watcher; end

# source://spring-watcher-listen//lib/spring/watcher/listen.rb#19
class Spring::Watcher::Listen < ::Spring::Watcher::Abstract
  # source://spring-watcher-listen//lib/spring/watcher/listen.rb#57
  def base_directories; end

  # source://spring-watcher-listen//lib/spring/watcher/listen.rb#49
  def changed(modified, added, removed); end

  # Returns the value of attribute listener.
  #
  # source://spring-watcher-listen//lib/spring/watcher/listen.rb#22
  def listener; end

  # source://spring-watcher-listen//lib/spring/watcher/listen.rb#24
  def start; end

  # source://spring-watcher-listen//lib/spring/watcher/listen.rb#31
  def stop; end

  # source://spring-watcher-listen//lib/spring/watcher/listen.rb#38
  def subjects_changed; end

  # @return [Boolean]
  #
  # source://spring-watcher-listen//lib/spring/watcher/listen.rb#45
  def watching?(file); end
end
