# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `turbolinks-source` gem.
# Please instead update this file by running `bin/tapioca gem turbolinks-source`.

# source://turbolinks-source//lib/turbolinks/source/version.rb#1
module Turbolinks; end

# source://turbolinks-source//lib/turbolinks/source/version.rb#2
module Turbolinks::Source
  class << self
    # source://turbolinks-source//lib/turbolinks/source.rb#5
    def asset_path; end
  end
end

# source://turbolinks-source//lib/turbolinks/source/version.rb#3
Turbolinks::Source::VERSION = T.let(T.unsafe(nil), String)
