# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `webpacker` gem.
# Please instead update this file by running `bin/tapioca gem webpacker`.

# source://webpacker//lib/webpacker.rb#6
module Webpacker
  extend ::Webpacker

  # source://webpacker//lib/webpacker.rb#35
  def bootstrap(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker.rb#35
  def clean(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker.rb#35
  def clobber(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker.rb#34
  def commands(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker.rb#35
  def compile(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker.rb#34
  def compiler(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker.rb#34
  def config(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker.rb#34
  def dev_server(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker.rb#25
  def ensure_log_goes_to_stdout; end

  # source://webpacker//lib/webpacker.rb#33
  def env(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker.rb#13
  def instance; end

  # source://webpacker//lib/webpacker.rb#9
  def instance=(instance); end

  # source://webpacker//lib/webpacker.rb#33
  def logger(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker.rb#33
  def logger=(arg); end

  # source://webpacker//lib/webpacker.rb#34
  def manifest(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker.rb#17
  def with_node_env(env); end
end

# source://webpacker//lib/webpacker/commands.rb#1
class Webpacker::Commands
  # @return [Commands] a new instance of Commands
  #
  # source://webpacker//lib/webpacker/commands.rb#4
  def initialize(webpacker); end

  # source://webpacker//lib/webpacker/commands.rb#24
  def bootstrap; end

  # source://webpacker//lib/webpacker/commands.rb#8
  def clean(count = T.unsafe(nil)); end

  # source://webpacker//lib/webpacker/commands.rb#19
  def clobber; end

  # source://webpacker//lib/webpacker/commands.rb#28
  def compile; end

  # source://webpacker//lib/webpacker/commands.rb#2
  def compiler(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker/commands.rb#2
  def config(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker/commands.rb#2
  def logger(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker/commands.rb#2
  def manifest(*_arg0, &_arg1); end

  private

  # source://webpacker//lib/webpacker/commands.rb#43
  def current_version; end

  # source://webpacker//lib/webpacker/commands.rb#35
  def versions; end
end

# source://webpacker//lib/webpacker/compiler.rb#4
class Webpacker::Compiler
  # @return [Compiler] a new instance of Compiler
  #
  # source://webpacker//lib/webpacker/compiler.rb#15
  def initialize(webpacker); end

  # source://webpacker//lib/webpacker/compiler.rb#19
  def compile; end

  # source://webpacker//lib/webpacker/compiler.rb#13
  def config(*_arg0, &_arg1); end

  # source://activesupport/6.0.6.1/lib/active_support/core_ext/module/attribute_accessors.rb#64
  def env; end

  # source://activesupport/6.0.6.1/lib/active_support/core_ext/module/attribute_accessors.rb#131
  def env=(obj); end

  # Returns true if all the compiled packs are up to date with the underlying asset files.
  #
  # @return [Boolean]
  #
  # source://webpacker//lib/webpacker/compiler.rb#36
  def fresh?; end

  # source://webpacker//lib/webpacker/compiler.rb#13
  def logger(*_arg0, &_arg1); end

  # Returns true if the compiled packs are out of date with the underlying asset files.
  #
  # @return [Boolean]
  #
  # source://webpacker//lib/webpacker/compiler.rb#41
  def stale?; end

  # source://activesupport/6.0.6.1/lib/active_support/core_ext/module/attribute_accessors.rb#64
  def watched_paths; end

  # source://activesupport/6.0.6.1/lib/active_support/core_ext/module/attribute_accessors.rb#131
  def watched_paths=(obj); end

  private

  # source://webpacker//lib/webpacker/compiler.rb#97
  def compilation_digest_path; end

  # source://webpacker//lib/webpacker/compiler.rb#88
  def default_watched_paths; end

  # source://webpacker//lib/webpacker/compiler.rb#48
  def last_compilation_digest; end

  # source://webpacker//lib/webpacker/compiler.rb#59
  def record_compilation_digest; end

  # source://webpacker//lib/webpacker/compiler.rb#64
  def run_webpack; end

  # source://webpacker//lib/webpacker/compiler.rb#53
  def watched_files_digest; end

  # source://webpacker//lib/webpacker/compiler.rb#101
  def webpack_env; end

  # Returns the value of attribute webpacker.
  #
  # source://webpacker//lib/webpacker/compiler.rb#46
  def webpacker; end

  class << self
    # source://activesupport/6.0.6.1/lib/active_support/core_ext/module/attribute_accessors.rb#57
    def env; end

    # source://activesupport/6.0.6.1/lib/active_support/core_ext/module/attribute_accessors.rb#124
    def env=(obj); end

    # source://activesupport/6.0.6.1/lib/active_support/core_ext/module/attribute_accessors.rb#57
    def watched_paths; end

    # source://activesupport/6.0.6.1/lib/active_support/core_ext/module/attribute_accessors.rb#124
    def watched_paths=(obj); end
  end
end

# source://webpacker//lib/webpacker/configuration.rb#5
class Webpacker::Configuration
  # @return [Configuration] a new instance of Configuration
  #
  # source://webpacker//lib/webpacker/configuration.rb#8
  def initialize(root_path:, config_path:, env:); end

  # @return [Boolean]
  #
  # source://webpacker//lib/webpacker/configuration.rb#54
  def cache_manifest?; end

  # source://webpacker//lib/webpacker/configuration.rb#58
  def cache_path; end

  # source://webpacker//lib/webpacker/configuration.rb#66
  def check_yarn_integrity=(value); end

  # @return [Boolean]
  #
  # source://webpacker//lib/webpacker/configuration.rb#70
  def check_yarn_integrity?; end

  # @return [Boolean]
  #
  # source://webpacker//lib/webpacker/configuration.rb#18
  def compile?; end

  # Returns the value of attribute config_path.
  #
  # source://webpacker//lib/webpacker/configuration.rb#6
  def config_path; end

  # source://webpacker//lib/webpacker/configuration.rb#14
  def dev_server; end

  # Returns the value of attribute env.
  #
  # source://webpacker//lib/webpacker/configuration.rb#6
  def env; end

  # source://webpacker//lib/webpacker/configuration.rb#62
  def extensions; end

  # @return [Boolean]
  #
  # source://webpacker//lib/webpacker/configuration.rb#78
  def extract_css?; end

  # source://webpacker//lib/webpacker/configuration.rb#50
  def public_manifest_path; end

  # source://webpacker//lib/webpacker/configuration.rb#46
  def public_output_path; end

  # source://webpacker//lib/webpacker/configuration.rb#42
  def public_path; end

  # source://webpacker//lib/webpacker/configuration.rb#30
  def resolved_paths; end

  # source://webpacker//lib/webpacker/configuration.rb#34
  def resolved_paths_globbed; end

  # Returns the value of attribute root_path.
  #
  # source://webpacker//lib/webpacker/configuration.rb#6
  def root_path; end

  # source://webpacker//lib/webpacker/configuration.rb#38
  def source_entry_path; end

  # source://webpacker//lib/webpacker/configuration.rb#22
  def source_path; end

  # source://webpacker//lib/webpacker/configuration.rb#26
  def source_path_globbed; end

  # @return [Boolean]
  #
  # source://webpacker//lib/webpacker/configuration.rb#74
  def webpack_compile_output?; end

  private

  # source://webpacker//lib/webpacker/configuration.rb#87
  def data; end

  # source://webpacker//lib/webpacker/configuration.rb#105
  def defaults; end

  # source://webpacker//lib/webpacker/configuration.rb#83
  def fetch(key); end

  # source://webpacker//lib/webpacker/configuration.rb#110
  def globbed_path_with_extensions(path); end

  # source://webpacker//lib/webpacker/configuration.rb#91
  def load; end
end

# source://webpacker//lib/webpacker/dev_server.rb#1
class Webpacker::DevServer
  # @return [DevServer] a new instance of DevServer
  #
  # source://webpacker//lib/webpacker/dev_server.rb#10
  def initialize(config); end

  # Returns the value of attribute config.
  #
  # source://webpacker//lib/webpacker/dev_server.rb#8
  def config; end

  # source://activesupport/6.0.6.1/lib/active_support/core_ext/module/attribute_accessors.rb#64
  def connect_timeout; end

  # source://activesupport/6.0.6.1/lib/active_support/core_ext/module/attribute_accessors.rb#131
  def connect_timeout=(obj); end

  # source://webpacker//lib/webpacker/dev_server.rb#54
  def env_prefix; end

  # source://webpacker//lib/webpacker/dev_server.rb#25
  def host; end

  # source://webpacker//lib/webpacker/dev_server.rb#46
  def host_with_port; end

  # @return [Boolean]
  #
  # source://webpacker//lib/webpacker/dev_server.rb#33
  def https?; end

  # source://webpacker//lib/webpacker/dev_server.rb#29
  def port; end

  # @return [Boolean]
  #
  # source://webpacker//lib/webpacker/dev_server.rb#50
  def pretty?; end

  # source://webpacker//lib/webpacker/dev_server.rb#42
  def protocol; end

  # @return [Boolean]
  #
  # source://webpacker//lib/webpacker/dev_server.rb#14
  def running?; end

  private

  # source://webpacker//lib/webpacker/dev_server.rb#63
  def defaults; end

  # source://webpacker//lib/webpacker/dev_server.rb#59
  def fetch(key); end

  class << self
    # source://activesupport/6.0.6.1/lib/active_support/core_ext/module/attribute_accessors.rb#57
    def connect_timeout; end

    # source://activesupport/6.0.6.1/lib/active_support/core_ext/module/attribute_accessors.rb#124
    def connect_timeout=(obj); end
  end
end

# source://webpacker//lib/webpacker/dev_server.rb#2
Webpacker::DevServer::DEFAULT_ENV_PREFIX = T.let(T.unsafe(nil), String)

# source://webpacker//lib/webpacker/dev_server_proxy.rb#3
class Webpacker::DevServerProxy < ::Rack::Proxy
  # @return [DevServerProxy] a new instance of DevServerProxy
  #
  # source://webpacker//lib/webpacker/dev_server_proxy.rb#6
  def initialize(app = T.unsafe(nil), opts = T.unsafe(nil)); end

  # source://webpacker//lib/webpacker/dev_server_proxy.rb#4
  def config(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker/dev_server_proxy.rb#4
  def dev_server(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker/dev_server_proxy.rb#12
  def perform_request(env); end

  private

  # source://webpacker//lib/webpacker/dev_server_proxy.rb#28
  def public_output_uri_path; end
end

# source://webpacker//lib/webpacker/railtie.rb#7
class Webpacker::Engine < ::Rails::Engine; end

# source://webpacker//lib/webpacker/env.rb#1
class Webpacker::Env
  # @return [Env] a new instance of Env
  #
  # source://webpacker//lib/webpacker/env.rb#10
  def initialize(webpacker); end

  # source://webpacker//lib/webpacker/env.rb#4
  def config_path(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker/env.rb#14
  def inquire; end

  # source://webpacker//lib/webpacker/env.rb#4
  def logger(*_arg0, &_arg1); end

  private

  # source://webpacker//lib/webpacker/env.rb#28
  def available_environments; end

  # source://webpacker//lib/webpacker/env.rb#20
  def current; end

  # source://webpacker//lib/webpacker/env.rb#24
  def fallback_env_warning; end

  class << self
    # source://webpacker//lib/webpacker/env.rb#6
    def inquire(webpacker); end
  end
end

# source://webpacker//lib/webpacker/env.rb#2
Webpacker::Env::DEFAULT = T.let(T.unsafe(nil), String)

# source://webpacker//lib/webpacker/helper.rb#1
module Webpacker::Helper
  # Computes the relative path for a given Webpacker asset.
  # Returns the relative path using manifest.json and passes it to asset_path helper.
  # This will use asset_path internally, so most of their behaviors will be the same.
  #
  # Example:
  #
  #   # When extract_css is false in webpacker.yml and the file is a css:
  #   <%= asset_pack_path 'calendar.css' %>  # => nil
  #
  #   # When extract_css is true in webpacker.yml or the file is not a css:
  #   <%= asset_pack_path 'calendar.css' %> # => "/packs/calendar-1016838bab065ae1e122.css"
  #
  # source://webpacker//lib/webpacker/helper.rb#20
  def asset_pack_path(name, **options); end

  # Computes the absolute path for a given Webpacker asset.
  # Returns the absolute path using manifest.json and passes it to asset_url helper.
  # This will use asset_url internally, so most of their behaviors will be the same.
  #
  # Example:
  #
  #   # When extract_css is false in webpacker.yml and the file is a css:
  #   <%= asset_pack_url 'calendar.css' %> # => nil
  #
  #   # When extract_css is true in webpacker.yml or the file is not a css:
  #   <%= asset_pack_url 'calendar.css' %> # => "http://example.com/packs/calendar-1016838bab065ae1e122.css"
  #
  # source://webpacker//lib/webpacker/helper.rb#37
  def asset_pack_url(name, **options); end

  # Returns the current Webpacker instance.
  # Could be overridden to use multiple Webpacker
  # configurations within the same app (e.g. with engines).
  #
  # source://webpacker//lib/webpacker/helper.rb#5
  def current_webpacker_instance; end

  # Creates a link tag for a favicon that references the named pack file.
  #
  # Example:
  #
  #  <%= favicon_pack_tag 'mb-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
  #  <link href="/packs/mb-icon-k344a6d59eef8632c9d1.png" rel="apple-touch-icon" type="image/png" />
  #
  # source://webpacker//lib/webpacker/helper.rb#59
  def favicon_pack_tag(name, **options); end

  # Creates an image tag that references the named pack file.
  #
  # Example:
  #
  #  <%= image_pack_tag 'application.png', size: '16x10', alt: 'Edit Entry' %>
  #  <img alt='Edit Entry' src='/packs/application-k344a6d59eef8632c9d1.png' width='16' height='10' />
  #
  # source://webpacker//lib/webpacker/helper.rb#49
  def image_pack_tag(name, **options); end

  # Creates a script tag that references the named pack file, as compiled by webpack per the entries list
  # in config/webpack/shared.js. By default, this list is auto-generated to match everything in
  # app/javascript/packs/*.js. In production mode, the digested reference is automatically looked up.
  #
  # Example:
  #
  #   <%= javascript_pack_tag 'calendar', 'data-turbolinks-track': 'reload' %> # =>
  #   <script src="/packs/calendar-1016838bab065ae1e314.js" data-turbolinks-track="reload"></script>
  #
  # source://webpacker//lib/webpacker/helper.rb#71
  def javascript_pack_tag(*names, **options); end

  # Creates script tags that reference the js chunks from entrypoints when using split chunks API,
  # as compiled by webpack per the entries list in config/webpack/shared.js.
  # By default, this list is auto-generated to match everything in
  # app/javascript/packs/*.js and all the dependent chunks. In production mode, the digested reference is automatically looked up.
  # See: https://webpack.js.org/plugins/split-chunks-plugin/
  # Example:
  #
  #   <%= javascript_packs_with_chunks_tag 'calendar', 'map', 'data-turbolinks-track': 'reload' %> # =>
  #   <script src="/packs/vendor-16838bab065ae1e314.chunk.js" data-turbolinks-track="reload"></script>
  #   <script src="/packs/calendar~runtime-16838bab065ae1e314.chunk.js" data-turbolinks-track="reload"></script>
  #   <script src="/packs/calendar-1016838bab065ae1e314.chunk.js" data-turbolinks-track="reload"></script>
  #   <script src="/packs/map~runtime-16838bab065ae1e314.chunk.js" data-turbolinks-track="reload"></script>
  #   <script src="/packs/map-16838bab065ae1e314.chunk.js" data-turbolinks-track="reload"></script>
  # DO:
  # <%= javascript_packs_with_chunks_tag 'calendar', 'map' %>
  # DON'T:
  # <%= javascript_packs_with_chunks_tag 'calendar' %>
  # <%= javascript_packs_with_chunks_tag 'map' %>
  #
  # source://webpacker//lib/webpacker/helper.rb#93
  def javascript_packs_with_chunks_tag(*names, **options); end

  # Creates a link tag, for preloading, that references a given Webpacker asset.
  # In production mode, the digested reference is automatically looked up.
  # See: https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content
  # Example:
  #
  #   <%= preload_pack_asset 'fonts/fa-regular-400.woff2' %> # =>
  #   <link rel="preload" href="/packs/fonts/fa-regular-400-944fb546bd7018b07190a32244f67dc9.woff2" as="font" type="font/woff2" crossorigin="anonymous">
  #
  # source://webpacker//lib/webpacker/helper.rb#104
  def preload_pack_asset(name, **options); end

  # Creates a link tag that references the named pack file, as compiled by webpack per the entries list
  # in config/webpack/shared.js. By default, this list is auto-generated to match everything in
  # app/javascript/packs/*.js. In production mode, the digested reference is automatically looked up.
  #
  # Note: If the development server is running and hot module replacement is active, this will return nothing.
  # In that setup you need to configure your styles to be inlined in your JavaScript for hot reloading.
  #
  # Examples:
  #
  #   # When extract_css is false in webpacker.yml:
  #   <%= stylesheet_pack_tag 'calendar', 'data-turbolinks-track': 'reload' %> # =>
  #   nil
  #
  #   # When extract_css is true in webpacker.yml:
  #   <%= stylesheet_pack_tag 'calendar', 'data-turbolinks-track': 'reload' %> # =>
  #   <link rel="stylesheet" media="screen" href="/packs/calendar-1016838bab065ae1e122.css" data-turbolinks-track="reload" />
  #
  # source://webpacker//lib/webpacker/helper.rb#128
  def stylesheet_pack_tag(*names, **options); end

  # Creates link tags that reference the css chunks from entrypoints when using split chunks API,
  # as compiled by webpack per the entries list in config/webpack/shared.js.
  # By default, this list is auto-generated to match everything in
  # app/javascript/packs/*.js and all the dependent chunks. In production mode, the digested reference is automatically looked up.
  # See: https://webpack.js.org/plugins/split-chunks-plugin/
  #
  # Examples:
  #
  #   <%= stylesheet_packs_with_chunks_tag 'calendar', 'map' %> # =>
  #   <link rel="stylesheet" media="screen" href="/packs/3-8c7ce31a.chunk.css" />
  #   <link rel="stylesheet" media="screen" href="/packs/calendar-8c7ce31a.chunk.css" />
  #   <link rel="stylesheet" media="screen" href="/packs/map-8c7ce31a.chunk.css" />
  # DO:
  # <%= stylesheet_packs_with_chunks_tag 'calendar', 'map' %>
  # DON'T:
  # <%= stylesheet_packs_with_chunks_tag 'calendar' %>
  # <%= stylesheet_packs_with_chunks_tag 'map' %>
  #
  # source://webpacker//lib/webpacker/helper.rb#151
  def stylesheet_packs_with_chunks_tag(*names, **options); end

  private

  # source://webpacker//lib/webpacker/helper.rb#170
  def resolve_path_to_image(name); end

  # source://webpacker//lib/webpacker/helper.rb#162
  def sources_from_manifest_entries(names, type:); end

  # source://webpacker//lib/webpacker/helper.rb#166
  def sources_from_manifest_entrypoints(names, type:); end

  # @return [Boolean]
  #
  # source://webpacker//lib/webpacker/helper.rb#158
  def stylesheet?(name); end
end

# source://webpacker//lib/webpacker/instance.rb#1
class Webpacker::Instance
  # @return [Instance] a new instance of Instance
  #
  # source://webpacker//lib/webpacker/instance.rb#6
  def initialize(root_path: T.unsafe(nil), config_path: T.unsafe(nil)); end

  # source://webpacker//lib/webpacker/instance.rb#34
  def commands; end

  # source://webpacker//lib/webpacker/instance.rb#22
  def compiler; end

  # source://webpacker//lib/webpacker/instance.rb#14
  def config; end

  # Returns the value of attribute config_path.
  #
  # source://webpacker//lib/webpacker/instance.rb#4
  def config_path; end

  # source://webpacker//lib/webpacker/instance.rb#26
  def dev_server; end

  # source://webpacker//lib/webpacker/instance.rb#10
  def env; end

  # source://activesupport/6.0.6.1/lib/active_support/core_ext/module/attribute_accessors.rb#64
  def logger; end

  # source://activesupport/6.0.6.1/lib/active_support/core_ext/module/attribute_accessors.rb#131
  def logger=(obj); end

  # source://webpacker//lib/webpacker/instance.rb#30
  def manifest; end

  # Returns the value of attribute root_path.
  #
  # source://webpacker//lib/webpacker/instance.rb#4
  def root_path; end

  class << self
    # source://activesupport/6.0.6.1/lib/active_support/core_ext/module/attribute_accessors.rb#57
    def logger; end

    # source://activesupport/6.0.6.1/lib/active_support/core_ext/module/attribute_accessors.rb#124
    def logger=(obj); end
  end
end

# Singleton registry for accessing the packs path using a generated manifest.
# This allows javascript_pack_tag, stylesheet_pack_tag, asset_pack_path to take a reference to,
# say, "calendar.js" or "calendar.css" and turn it into "/packs/calendar-1016838bab065ae1e314.js" or
# "/packs/calendar-1016838bab065ae1e314.css".
#
# When the configuration is set to on-demand compilation, with the `compile: true` option in
# the webpacker.yml file, any lookups will be preceded by a compilation if one is needed.
#
# source://webpacker//lib/webpacker/manifest.rb#8
class Webpacker::Manifest
  # @return [Manifest] a new instance of Manifest
  #
  # source://webpacker//lib/webpacker/manifest.rb#13
  def initialize(webpacker); end

  # source://webpacker//lib/webpacker/manifest.rb#11
  def compiler(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker/manifest.rb#11
  def config(*_arg0, &_arg1); end

  # source://webpacker//lib/webpacker/manifest.rb#11
  def dev_server(*_arg0, &_arg1); end

  # Computes the relative path for a given Webpacker asset using manifest.json.
  # If no asset is found, returns nil.
  #
  # Example:
  #
  #   Webpacker.manifest.lookup('calendar.js') # => "/packs/calendar-1016838bab065ae1e122.js"
  #
  # source://webpacker//lib/webpacker/manifest.rb#41
  def lookup(name, pack_type = T.unsafe(nil)); end

  # Like lookup, except that if no asset is found, raises a Webpacker::Manifest::MissingEntryError.
  #
  # source://webpacker//lib/webpacker/manifest.rb#48
  def lookup!(name, pack_type = T.unsafe(nil)); end

  # source://webpacker//lib/webpacker/manifest.rb#21
  def lookup_pack_with_chunks(name, pack_type = T.unsafe(nil)); end

  # source://webpacker//lib/webpacker/manifest.rb#31
  def lookup_pack_with_chunks!(name, pack_type = T.unsafe(nil)); end

  # source://webpacker//lib/webpacker/manifest.rb#17
  def refresh; end

  private

  # source://webpacker//lib/webpacker/manifest.rb#57
  def compile; end

  # @return [Boolean]
  #
  # source://webpacker//lib/webpacker/manifest.rb#53
  def compiling?; end

  # source://webpacker//lib/webpacker/manifest.rb#61
  def data; end

  # source://webpacker//lib/webpacker/manifest.rb#69
  def find(name); end

  # source://webpacker//lib/webpacker/manifest.rb#73
  def full_pack_name(name, pack_type); end

  # @raise [Webpacker::Manifest::MissingEntryError]
  #
  # source://webpacker//lib/webpacker/manifest.rb#78
  def handle_missing_entry(name); end

  # source://webpacker//lib/webpacker/manifest.rb#82
  def load; end

  # The `manifest_name` method strips of the file extension of the name, because in the
  # manifest hash the entrypoints are defined by their pack name without the extension.
  # When the user provides a name with a file extension, we want to try to strip it off.
  #
  # source://webpacker//lib/webpacker/manifest.rb#93
  def manifest_name(name, pack_type); end

  # source://webpacker//lib/webpacker/manifest.rb#98
  def manifest_type(pack_type); end

  # source://webpacker//lib/webpacker/manifest.rb#106
  def missing_file_from_manifest_error(bundle_name); end
end

# source://webpacker//lib/webpacker/manifest.rb#9
class Webpacker::Manifest::MissingEntryError < ::StandardError; end
